"""empty message

Revision ID: 691ef1efdf3e
Revises: aef1646f0ac8
Create Date: 2021-02-17 16:20:24.595658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691ef1efdf3e'
down_revision = 'aef1646f0ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todo', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'list_id')
    op.drop_table('todolists')
    # ### end Alembic commands ###
