"""empty message

Revision ID: aef1646f0ac8
Revises: eb1e3e2e0b22
Create Date: 2021-02-16 11:22:26.729768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef1646f0ac8'
down_revision = 'eb1e3e2e0b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    op.execute('UPDATE todo SET completed = False WHERE completed IS NULL;')

    op.alter_column('todo', 'completed', nullable=False)
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
